registry: public.ecr.aws/datadog
datadog:
  site: us5.datadoghq.com
  tags:
    - env:dev
  apm:
    enabled: true
    instrumentation:
      enabled: true
      # enabledNamespaces:
      #   - default
  env:
    - name: DD_APM_ENABLED
      value: "true"
  logs:
    enabled: true
    containerCollectAll: true
